### ISSUE TITLE
Campo presente e vazio gera LangDetectException: No features in text

### ISSUE THREAD

**Issue by dineiar** [ppgcc/GenerateReportBib#2]
Se o campo sendo processado está presente, mas vazio, o script lança uma exceção.

Por exemplo, na entrada abaixo o campo `INSTITUTION` está presente, mas vazio:
```bibtex
@techreport{Kitchenham2007,
	title={Guidelines for performing systematic literature reviews in software engineering},
	author={Kitchenham, Barbara and Charters, Stuart},
	NUMBER = {EBSE-2007-01},
	INSTITUTION = {},
	ADDRESS = {Durham, UK},
	year={2007},
	publisher={Citeseer}
}
```

Gera a exceção:
```
Traceback (most recent call last):
  File "grb.py", line 695, in <module>
    main()
  File "grb.py", line 351, in main
    msg_gen, bib = regenerate_bib(bib, REQ)
  File "grb.py", line 520, in regenerate_bib
    school_capitalize, phrase_cap = check_parentheses_and_capitalize(phrase)
  File "grb.py", line 597, in check_parentheses_and_capitalize
    language = detect(phrase)
  File "/home/dineir/.local/lib/python3.8/site-packages/langdetect/detector_factory.py", line 130, in detect
    return detector.detect()
  File "/home/dineir/.local/lib/python3.8/site-packages/langdetect/detector.py", line 136, in detect
    probabilities = self.get_probabilities()
  File "/home/dineir/.local/lib/python3.8/site-packages/langdetect/detector.py", line 143, in get_probabilities
    self._detect_block()
  File "/home/dineir/.local/lib/python3.8/site-packages/langdetect/detector.py", line 150, in _detect_block
    raise LangDetectException(ErrorCode.CantDetectError, 'No features in text.')
langdetect.lang_detect_exception.LangDetectException: No features in text.
```

Um campo vazio deveria ser considerado um campo ausente.

**Comment by dineiar** [comment]
O PR #3 resolve esta issue.
